SELECT B.HOUR
, NVL(A.COUNT,0)
FROM 
(SELECT TO_CHAR(DATETIME,'HH24') AS "HOUR"
, COUNT(TO_CHAR(DATETIME,'HH24')) AS "COUNT"
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME,'HH24')) A, 
(SELECT ROWNUM-1 AS HOUR FROM DUAL CONNECT BY LEVEL <= 24) B
 WHERE A.HOUR(+) = B.HOUR
ORDER BY B.HOUR
